version : "3"
services:
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - MONGO_USER=root
      - MONGO_PASSWORD=123456789
    command: npm run dev