version : "3"
services:
  node-app:
    build: . 
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   -./env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123321
    volumes:
      - mongo-db:/data/db
    
  
volumes:
  mongo-db:
    